name: flutter_mrz_scanner
description: Scans MRZ (Machine Readable Zone) from identity documents for iOS and Android.
version: 1.0.0+1
authors:
  - Oleksandr Leuschenko <olexa.le@gmail.com>
  - Anna Domashych <anna.domashych@gmail.com>
homepage: https://github.com/olexale/flutter_mrz_scanner

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mrz_parser: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.github.olexale.flutter_mrz_scanner
    pluginClass: FlutterMrzScannerPlugin
